app_1/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    path('', auth_views.LoginView.as_view(), name='login'),
    path('home',views.interface_list,name='home'),
    path('add_interface/',views.add_interface,name='add_interface'),
    path('approve/',views.approve,name='approve'),
    path('assign/',views.assign,name='assign'),
    path('modify/<int:modify_pk>',views.modify,name='modify'),
    path('logout/', auth_views.LogoutView.as_view(), name='logoutuser'),
    path('interface_detail/<int:num>',views.interface_detail,name='interface_detail'),
    path('detail/<int:pk>',views.detail,name='detail'),
    path('detail_modify/<int:detail_modify>',views.detail_modify,name='detail_modify'),
    path('interface_filter',views.filter_interface,name='interface_filter'),
    path('field_detail/<int:interface_detail>',views.field_detail,name='field_detail'),
]

# path('logoutuser',views.logout,name='logoutuser'),

map_tool/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app_1.urls'))
]

app_1/models.py
from django.db import models
from django.contrib.auth.models import User

publisher_schema_options = (('TS', 'Trade Stone'),('O','Others'))
subscriber_schema_options = (('RMS','RMS'),('DMS','DMS'))

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    company_name = models.CharField(max_length=100)

class InterfaceType(models.Model):
    name=models.CharField(max_length=50,blank=True)
    def __str__(self):
        return self.name

    
class Interface(models.Model):
    interface=models.CharField(max_length=50)
    description=models.CharField(max_length=100)
    publisher=models.CharField(max_length=50)
    publisher_schema=models.CharField(max_length=4,choices=publisher_schema_options)
    subscriber=models.CharField(max_length=50)
    subscriber_schema=models.CharField(max_length=4,choices=subscriber_schema_options)
    created_by=models.ForeignKey(User,on_delete=models.CASCADE)
    created_on=models.DateField(blank=True,null=True)
    updated_by=models.ForeignKey(User,blank=True,null=True,on_delete=models.CASCADE,related_name='updateby')
    updated_on=models.DateField(blank=True,null=True,) 
    interface_type = models.ForeignKey(InterfaceType,on_delete=models.CASCADE)
    approve_by=models.ForeignKey(User,blank=True,null=True,on_delete=models.CASCADE,related_name='approveby')
    approve_on=models.DateField(auto_now=True,blank=True,null=True,) 
    assignee = models.ForeignKey(User,on_delete=models.CASCADE,related_name='assign_to',blank=True,null=True,)
    assign_on = models.DateField(auto_now=True,blank=True,null=True,)
    def __str__(self):
        return self.interface


class InterfaceDetail(models.Model):
    interface=models.ForeignKey(Interface,on_delete=models.CASCADE,null=True)
    description=models.CharField(max_length=50) 
    comments=models.CharField(max_length=50) 
    created_by=models.ForeignKey(User,on_delete=models.CASCADE)
    created_on=models.DateField(blank=True,null=True)
    updated_by=models.ForeignKey(User,blank=True,null=True,on_delete=models.CASCADE,related_name='update_by')
    updated_on=models.DateField(blank=True,null=True,) 


class SchemaTable(models.Model):
    schema_name =models.CharField(max_length=50)  
    table_name  =models.CharField(max_length=50)  
    column_name =models.CharField(max_length=50)   
    field_type  =models.CharField(max_length=50,blank=True)  
    field_length =models.CharField(max_length=50,blank=True) 
    properties  =models.CharField(max_length=50,blank=True)  
    default_value =models.CharField(max_length=100,blank=True) 

class InterfacefieldDetail(models.Model):
    field=models.ForeignKey(InterfaceDetail,on_delete=models.CASCADE)    
    pub_table =models.CharField(max_length=50)        
    pub_column  =models.CharField(max_length=50)        
    pub_field_type =models.CharField(max_length=50)     
    pub_field_length =models.CharField(max_length=50)   
    pub_column_seq   = models.IntegerField(blank=True,null=True)             
    pub_properties  =models.CharField(max_length=50)    
    pub_default_value =models.CharField(max_length=100,blank=True)  
    pub_min_occurs  = models.IntegerField(blank=True,null=True)                  
    pub_max_occurs  = models.IntegerField(blank=True,null=True)                  
    sub_table  =models.CharField(max_length=50)         
    sub_column =models.CharField(max_length=50)         
    sub_field_type =models.CharField(max_length=50)    
    sub_field_length =models.CharField(max_length=50)   
    sub_column_seq  = models.IntegerField(blank=True,null=True)              
    sub_properties =models.CharField(max_length=50)     
    sub_default_value =models.CharField(max_length=50)  
    sub_min_occurs  = models.IntegerField(blank=True,null=True)                  
    sub_max_occurs  = models.IntegerField(blank=True,null=True)                 
    Conversion_rule =models.CharField(max_length=250)    
    Comments  =models.CharField(max_length=250,blank=True)       
    Created_by =models.ForeignKey(User,on_delete=models.CASCADE,related_name='created_by')      
    Created_on =models.DateField(blank=True,null=True)    
    Updated_by =models.ForeignKey(User,on_delete=models.CASCADE,related_name='updated_by')
    Updated_on =models.DateField(blank=True,null=True)   

app_1/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.models import User
from datetime import datetime
from .models import Interface, InterfaceType,InterfaceDetail, InterfacefieldDetail as IFD
from .forms import InterfaceForm, InterfaceTypeForm,AssigneeForm,ModifyForm,DetailForm,InterfacedetailForm,InterfacefieldDetail,SchemaTable
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required




@login_required(login_url='login')
def interface_list(request):

    form = InterfaceTypeForm()
    assigneeform = AssigneeForm()
    interfaces=None
    if 'interface_type' in request.session:
        id=request.session['interface_type']
        interfaces=Interface.objects.filter(interface_type=id)
        form.fields['interface_type'].initial=id
    users = User.objects.all()
    return render(request,'interface.html',{'interfaces':interfaces,'form':form, 'assigneeform':assigneeform, 'users':users,})

@login_required(login_url='login')
def filter_interface(request):
    id=request.GET.get('id')
    request.session['interface_type']=id
    interfaces=Interface.objects.filter(interface_type=id)
    data=dict()
    data['html']=render_to_string('interface_filter.html',{'interfaces':interfaces})
    return JsonResponse(data)



@login_required(login_url='login')
def add_interface(request):
    if request.method == 'POST':
        int_type = InterfaceType.objects.get(id=request.session['interface_type'])
        user=User.objects.get(username=request.POST.get('created_by'))
        updated_request = request.POST.copy()
        updated_request.update({'created_by': user,'updated_by': user})
        form = InterfaceForm(updated_request)
        if form.is_valid():
            interface = form.save(commit=False)
            interface.interface_type = int_type
            interface.save()
            return redirect('home')

        
    else:
        form = InterfaceForm()
        form.fields['created_by'].initial = request.user.username
        form.fields['created_on'].initial = datetime.now().date()
        form.fields['updated_by'].initial = request.user.username
        form.fields['updated_on'].initial = datetime.now().date()
        request.session['interface_type'] = request.GET.get('interface_type')
        return render(request,'add_interface.html',{'form':form})

#assign
@login_required(login_url='login')
def assign(request):
    data = dict()
    id = request.GET.get('interface')
    assignee_name = request.GET.get('assignee')
    print(assignee_name)
    interface = Interface.objects.get(id=id)
    user = User.objects.get(username=assignee_name)
    interface.assignee = user
    interface.assign_on = datetime.now().date()
    data['user'] = interface.assignee.username
    data['date'] = interface.assign_on
    interface.save(update_fields=['assignee','assign_on'])
    return JsonResponse(data)



# approve
@login_required(login_url='login')
def approve(request):
    data = dict()
  
    id = request.GET.get('interface')
    interface = Interface.objects.get(id=id)
    if interface.approve_by==None:
        interface.approve_by=request.user
        interface.approve_on = datetime.now().date()
        data['user'] = interface.approve_by.username
        data['date'] = interface.approve_on
    else:
        interface.approve_by=None
        interface.approve_on = None
        data['user'] = None
        data['date'] = None

    # interface.approveby = interface.createdby
    # interface.approveon = datetime.today()
    interface.save(update_fields=['approve_by','approve_on'])
    return JsonResponse(data)

# modify

@login_required(login_url='login')
def modify(request,modify_pk):
    
    interface = get_object_or_404(Interface,pk=modify_pk)
    if request.method=="GET":
        form=ModifyForm()
        form.fields['interface'].initial = interface.interface
        form.fields['description'].initial = interface.description
        form.fields['publisher'].initial = interface.publisher
        form.fields['publisher_schema'].initial = interface.publisher_schema
        form.fields['subscriber'].initial = interface.subscriber
        form.fields['subscriber_schema'].initial = interface.subscriber_schema
        form.fields['created_by'].initial = request.user.username
        form.fields['created_on'].initial = interface.created_on

        form.fields['updated_by'].initial = request.user.username
        form.fields['updated_on'].initial = interface.updated_on
        return render(request,'modify.html',{'form':form})

    else:
        user=User.objects.get(username=request.POST.get('created_by'))
        updated_request = request.POST.copy()
        updated_request.update({'created_by': user,'updated_by':user})
        form = ModifyForm(updated_request,instance=interface)
        if form.is_valid():
            # form=InterfacedetailForm(request.POST,instance=interface)
            detail=form.save(commit=False)
            detail.save()
            return redirect('home')


        form=ModifyForm(request.POST,instance=interface)
        form.save()
        return redirect('home')


#  logout
@login_required(login_url='login')
def interface_detail(request,num):
    
    interfacedetail=InterfaceDetail.objects.filter(interface=num)
    interface = get_object_or_404(Interface,pk=num)
    if request.method=="GET":
        
        form=DetailForm()
        form.fields['interface'].initial = interface.interface
        form.fields['description'].initial = interface.description
        return render(request,'interface_detail.html',{'form':form,'interfacedetail':interfacedetail,'id':interface.id})

@login_required(login_url='login')
def detail(request,pk):
    interface=Interface.objects.get(id=pk)
    if request.method=="GET":
        form=InterfacedetailForm()
        form.fields['created_by'].initial = request.user.username
        form.fields['created_on'].initial = datetime.now().date()
        form.fields['updated_by'].initial = request.user.username
        form.fields['updated_on'].initial = datetime.now().date()
        return render(request,'detail.html',{'form':form,'id':interface.id})
    else:
        user=User.objects.get(username=request.POST.get('created_by'))
        updated_request = request.POST.copy()
        updated_request.update({'created_by': user,'updated_by': user})
        form = InterfacedetailForm(updated_request)
        if form.is_valid():
            # form=InterfacedetailForm(request.POST)
            detail=form.save(commit=False)
            detail.interface=interface
            detail.save()
            return redirect('interface_detail',num=interface.id)


@login_required(login_url='login')
def detail_modify(request,detail_modify):
    
    interface = get_object_or_404(InterfaceDetail,pk=detail_modify)
    if request.method=="GET":
        form=InterfacedetailForm()
        form.fields['description'].initial = interface.description
        form.fields['comments'].initial = interface.comments
        form.fields['created_by'].initial = request.user.username
        form.fields['created_on'].initial = interface.created_on
        form.fields['updated_by'].initial = request.user.username
        form.fields['updated_on'].initial = interface.created_on
        return render(request,'detail_modify.html',{'form':form,'id':interface.id})

    else:
        user=User.objects.get(username=request.POST.get('created_by'))
        updated_request = request.POST.copy()
        updated_request.update({'created_by': user,'updated_by':user})
        form = InterfacedetailForm(updated_request,instance=interface)
        if form.is_valid():
            # form=InterfacedetailForm(request.POST,instance=interface)
            detail=form.save(commit=False)
            detail.save()
            return redirect('interface_detail',num=interface.interface.id)
@login_required(login_url='login')
def field_detail(request,interface_detail):
    interface = get_object_or_404(InterfaceDetail,pk=interface_detail)
    if_details = IFD.objects.filter(field=interface)
    if request.method=='GET':
        form = InterfacefieldDetail()
        form.fields['Created_by'].initial = request.user.username
        form.fields['Created_on'].initial = datetime.now().date()
        form.fields['Updated_by'].initial = request.user.username
        form.fields['Updated_on'].initial = datetime.now().date()
        
    else:
        user=User.objects.get(username=request.POST.get('Created_by'))
        updated_request = request.POST.copy()
        updated_request.update({'Created_by': user,'Updated_by':user})
        form=InterfacefieldDetail(updated_request)
        if form.is_valid():
            
            interface_field_detail = form.save(commit=False)
            interface_field_detail.field = interface
            interface_field_detail.save()
            # form = InterfacefieldDetail()
            
            return redirect('field_detail',interface_detail=interface_detail)
    return render(request,'field_detail.html',{'form':form,'if_details':if_details,'id':interface.interface.id})

app_1/templates/add_interface.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

    <div class="page-wrapper bg-gra-03 p-t-45 p-b-50">
        <div class="wrapper wrapper--w790">
            <div class="card card-5" >
                <div class="card-heading">
                    <h2 class="title">Interface Header Information</h2>
                    <h2 class="title2" >Use this Screen to setup interface information</h2>
                </div>
                <div class="card-body" >
                    <form method="POST">
                      {% csrf_token %}
                      {% for field in form %}
                        <div class="form-row">
                            <div class="name">{{field.label_tag}}</div>
                            <div class="value">
                                <div class="input-group">
                                  {{field}}
                                </div>
                            </div>
                        </div>
                      {% endfor %}
                        <div>
                            <button class="btn btn-primary " type="submit">save</button>
                            <a href="{% url 'home' %}" >Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>    


<!-- end document-->










<!-- <div class="container" style="background-color:rgb(197, 188, 139)"> 
<center>
<div class="form-group " style="margin-top: 4%;">
   <h3 style="color:#4E342E;font-family: 'Mulish', sans-serif;">Interface Header Information</h3><hr style="background-color: white;height:1px;width:200px">
      <h6>Use this Screen to setup interface information</h6><br>
 <form method="post" class="form-horizontal">
  {% csrf_token %}
  {% for field in form  %}
  <div class="row" ></div>
    <b style="font-size: 16px;font-family: 'Mulish', sans-serif;">{{ field.label_tag }}</b>&nbsp; <b>{{ field }}</b>
  {% endfor %}
  <div class="form-group"><BR>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <button type="submit" class="btn btn-success">
        <span class="glyphicon glyphicon-ok"></span> Save
      </button>
      <a href="{% url 'home' %}" class="btn btn-default">Cancel</a>
    </di
</center>
</div> 
</div> 





<h2>Add interface</h2>
<div class="container" style="background-color: #dfe6e9" >
  <div class="row" style="justify-content: center;height:50%">
    <div class="col-lg-6">
      <form method='POST'> 
      {% csrf_token %}

      {{form.as_p}}

      <input type='submit'>
      <button type="button"><a href="{% url 'home' %}">Exit</a></button>
    </div>
  </div>
</div> -->

 




{% endblock %}

app_1/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link href="{% static 'css1/main.css' %}" rel="stylesheet" media="all">
	  <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <style>
            /*old one table*/
              table, th, td {
                border: 1px solid rgb(14, 13, 13);
                border-collapse: collapse;
                
                
              }
              th, td {
                padding: 1px;
                text-align: center;
                font-size: 15px;
                font-family:sans-serif;
               
              }
            </style>
    <title>Mapping tool!</title>
  </head>
  <body>

    {% block content%}
    {% endblock %}
   </body>
</html>

app_1/templates/interface.html
{% extends 'base.html' %}
{% load static %}
{% block content  %}


<body  >

<div class="wrapper">

  <header>
      <h1 class="title">Interface Header Screen</h1>
  </header><br>

<div class="columns">
    <div class="column" style="border: none;">
      <form action="{% url 'add_interface' %}">
        {% for field in form %}
        <div class="form-row">
          <div class="name" style="color: black;">{{field.label_tag}} </div>
          <div class="value">
              <div class="input-group">
                  {{field}}
              </div>
          </div>
        </div>
        {% endfor %}
        <button class="btn btn-primary"  type="submit" >add interface</button>
      </form>
  </div>



</section>
  <footer >
    <button class="btn btn-primary" id= "assign" >Assign</button>
    <button class="btn btn-primary"  onclick="myFunction()" value="approve" id="approve">Approve</button><br><br>
    <button class="btn btn-primary"  id="interfacedetail" > interface detail</button>
    
    <button class="btn btn-primary" id= "modify" >modify interface</button>
  
  </footer>
  {% if user.is_authenticated %}
  <form action="{% url 'logoutuser' %}" >
    <button type="submit" class="btn btn-primary" >
      Logout
    </button>
  </form>
  {% endif%}
</div> 
</div>



  <div class="row">
    <div class="col-md-12">
        <table class="table table-striped table-sm table-hover" id="interface_table"> 
                <tr>
                 <th>select</th>
                 <th>TypeName</th>
                 <th>interface</th>
                 <th>Description</th>
                 <th>Publisher</th>
                 <th>Pubschema</th>
                 <th>Subscriber</th>
                 <th>Subschema</th>
                 <th>Assignee</th>
                 <th>Assignon</th>
                 <th>Approver</th>
                 <th>Approveron</th>
                 <th>Updatedby</th>
                 <th>Updatedon</th>
                 <th>Createdby</th>
                 <th>Createdon</th>
               </tr>
               {% for interface in interfaces %}
               <tr>
                   <td><input type="checkbox" id="int_{{interface.id}}" name="cb" data="{{interface.id}}" user="{{interface.created_by}}"></td>
                   <td>{{interface.interface_type.name}}</td>
                   <td>{{interface.interface}}</td>
                   <td>{{interface.description}}</td>
                   <td>{{interface.publisher}}</td>
                   <td>{{interface.publisher_schema}}</td>
                   <td>{{interface.subscriber}}</td>
                   <td>{{interface.subscriber_schema}}</td>
                   <td id="assignee{{interface.id}}">
                    {% if interface.assignee != None %}
                     {{interface.assignee}}
                    {% else %}

                    {% endif %}
                    </td>  
                   <td id="assignon{{interface.id}}">
                    {% if interface.assignee != None %}
                     {{interface.assign_on}}
                    {% else %}

                    {% endif %}
                  </td>
                   <td id="by{{interface.id}}">
                    {% if interface.approve_by != None %}
                        {{interface.approve_by}}
                    {% else %}
                      
                    {% endif %}
                </td>
                <td id="on{{interface.id}}">
                    {% if interface.approve_by != None %}
                        {{interface.approve_on}}
                    {% else %}
                      
                    {% endif %}
                </td>
                   
                   <td>{{interface.updated_by}}</td>
                   <td>{{interface.updated_on}}</td>
                   <td>{{interface.created_by}}</td>
                   <td>{{interface.created_on}}</td>
               </tr>
               {% endfor %}
            </table>
</div>

<div class="modal" id="AssignModal">
    <div class="modal-content">

        <span class="close">&times;</span>
        <button id="search" class="btn btn-info">Search Assignee</button>
      <form>
          <table>
            {% csrf_token %}
            {{assigneeform}}
          </table>
          <button type="button" id="modalassign" class="btn btn-outline-success">Assign</button>
      </form>
    </div>
</div>

<div class="modal" id="searchassignee">
    <div class="modal-content">

        <span class="close">&times;</span>
      <table>
          {% for user in users %}
          
            <tr>
                
                    <td style="background-color: burlywood;"><a data="{{user}}" data_fname="{{user.first_name}}" 
                        data_lname="{{user.last_name}}"
                        data_active="{{user.is_active}}"
                        data_company= "{{user.profile.company_name}}"
                        
                        class="select_user" href="#">{{user.first_name}}</a></td>
                    <td style="background-color: burlywood;">{{user.last_name}}</td>
                
            </tr>
        

          {% endfor %}
      </table>
    </div>
</div>

<!-- js/ajax -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script>
  $(document).ready(function(){
    var  assignee;
    $('#id_interface_type').change(function(){
      var id = $(this).val();
      $.ajax({
        url:'/interface_filter',
        data:{'id':id},
        success:function(data){
          $('#interface_table').html(data.html);
        }
      });

    });
   $('#approve').prop('disabled', true);
   $('#assign').prop('disabled', true);
   $('#modify').prop('disabled', false);
   $('#interfacedetail').prop('disabled', false);
   
   $("#AssignModal").css('display',"none");
   
   $(".close").click(function(){
        $("#AssignModal").css('display',"none");
        $("#searchassignee").css('display',"none");
   });

   $(".select_user").click(function(){
        event.preventDefault();
        $('#id_username').val($(this).attr('data'));
        $('#id_first_name').val($(this).attr('data_fname'));
        $('#id_last_name').val($(this).attr('data_lname'));
        $('#id_is_active').val($(this).attr('data_active'));
        $('#id_company_name').val($(this).attr('data_company'));
        $("#searchassignee").css('display',"none");
   });

    $("#assign").click(function(){
        $("#AssignModal").css('display',"block");
    });

    $("#search").click(function(){
        $("#searchassignee").css('display',"block");
    });


    $("#modalassign").click(function(){
      event.preventDefault();
      assignee = $('#id_username').val();
      
      var tomodify = [];
      var user=[];
          $.each($("input[name='cb']:checked"), function(){
                  tomodify.push($(this).attr('data'));
                  user.push($(this).attr('user'));      
      
              });
              $.ajax({
                url: "/assign/",
                data : {'interface':tomodify[0],'assignee':assignee}, 
                success: function(result)
                {
                     
                     $('#assignee'+tomodify[0]).html(result.user);
                                
                      $('#assignon'+tomodify[0]).html(result.date);
             
              
                      $('#approve').prop('disabled', true);
                      $('#assign').prop('disabled', true);
                      $("#AssignModal").css('display',"none");
                      $("#int_"+tomodify[0]). prop("checked", false);

                }
    });

    });


   $("#approve").click(function(){
    
   
    var tomodify = [];
    var user=[];
          $.each($("input[name='cb']:checked"), function(){
                  tomodify.push($(this).attr('data'));
                  user.push($(this).attr('user'));      
      
              });
             //alert(tomodify[0]);
                           
      $.ajax({
      url: "/approve/",
      data : {'interface':tomodify[0]}, 
      success: function(result)
      {
             // alert(result.user,result.date);
              $('#by'+tomodify[0]).html(result.user);
             
              if(result.user==null)
              {
               $('#on'+tomodify[0]).html("");
              }
              else{
                $('#on'+tomodify[0]).html(result.date);
              }
              
              $('#approve').prop('disabled', true);
              $('#assign').prop('disabled', true);
              $("#int_"+tomodify[0]). prop("checked", false);

          }
    });
    });

    $('table').on('click','input[type="checkbox"]',function(){
     if($(this). prop("checked") == true){

        $('#approve').prop('disabled', false);
        $('#assign').prop('disabled',false)

        }
     else if($(this). prop("checked") == false){
        $('#approve').prop('disabled', true); 
        $('#assign').prop('disabled', true);
     }
   });
  

  $("#interfacedetail").click(function(){ 
   
    var tomodify = [];
          $.each($("input[name='cb']:checked"), function(){
                  tomodify.push($(this).attr('data'));
                  
                  var id =tomodify[0];  
                  var url="/interface_detail";
                  document.location.href= url  + "/" + id;
                  
      
              });
          //alert(tomodify[0]);
    });
    /*$('table').on('click','input[type="checkbox"]',function(){
      if($(this). prop("checked") == true){
  
         $('#interfacedetail').prop('disabled', false); 
      }
  
      else if($(this). prop("checked") == false){
          $('#interfacedetail').prop('disabled', true);
      }
     })*/

  /* modify*/

  $("#modify").click(function(){ 
   
    var tomodify = [];
          $.each($("input[name='cb']:checked"), function(){
                  tomodify.push($(this).attr('data'));
                  
                  var id =tomodify[0];  
                  var url="/modify";
                  document.location.href= url  + "/" + id;
                  
      
              });
          //alert(tomodify[0]);
    });
    /*$('table').on('click','input[type="checkbox"]',function(){
      if($(this). prop("checked") == true){
  
         $('#modify').prop('disabled', false); 
      }
  
      else if($(this). prop("checked") == false){
          $('#modify').prop('disabled', true);
      }
     })*/
  
    });
  
    function myFunction() {

      var btn = document.getElementById("approve");
  
      if (btn.value == "approve") {
          btn.value = "un-approve";
          btn.innerHTML = "un-approve";
      }
      else {
          btn.value = "approve";
          btn.innerHTML = "approve";
      }
  
  }

  </script>


<style>
  body {font-family: Arial, Helvetica, sans-serif;}
  
  /* The Modal (background) */
  .modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
  }
  
  /* Modal Content */
  .modal-content {
    background-color: #e4e0e0;
    margin: auto;
    padding: 20px;
    border: 1px solid #888;
    width: 80%;
  }
  
  /* The Close Button */
  .close {
    color: #aaaaaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
  }
  
  .close:hover,
  .close:focus {
    color: #000;
    text-decoration: none;
    cursor: pointer;
  }
  table{
    table-layout: fixed;
  }
  @media screen and (max-width: 680px) {
    .columns .column {
      flex-basis: 100%;
      margin: 0 0 5px 0;
    }
    .table{
      table-layout: auto;
    }
  }
  @media screen and (max-width: 980px) {
    .columns .column {
      margin-bottom: 5px;
      flex-basis: 40%;
    }
  }
  body{
    background-color: rgb(201, 198, 196);
  }
  .wrapper{
    background-color: rgba(19, 22, 27, 0.411);;
  }
  .btn{
    background-color: rgb(74, 105, 172);
  }

  </style>

















{% endblock %}